[package]
name = "sixsixsix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "6.4.0"
lunar_rust = "1.0.1"
chrono = "0.4"
