name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

# 添加权限配置
permissions:
  contents: write

jobs:
  build-linux-gnu:
    name: Build Linux GNU
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Prepare binary
        shell: bash
        run: |
          mkdir -p release
          cp target/release/sixsixsix release/sixsixsix_linux_gnu

      - name: Upload linux gnu artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-gnu
          path: release/*

  build-linux-musl:
    name: Build Linux MUSL
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache curl rust cargo

      - name: Build binary
        run: cargo build --release

      - name: Prepare binary
        run: |
          mkdir -p release
          cp target/release/sixsixsix release/sixsixsix_linux_musl

      - name: Upload linux musl artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-musl
          path: release/*

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Prepare binary
        shell: bash
        run: |
          mkdir -p release
          cp target/release/sixsixsix.exe release/sixsixsix.exe

      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows 
          path: release/*
          pattern: binaries-*  # 关键修改：仅下载构建产物 artifacts
          merge-multiple: true  # 关键修改：合并所有 artifact 到同一目录

  release:
    name: Create Release
    needs: [build-linux-gnu, build-linux-musl, build-windows]
    runs-on: ubuntu-latest
    # 也可以在这里单独设置权限
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 添加这行获取触发工作流的 tag
          files: |
            release/sixsixsix*  # 匹配所有可执行文件
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
